CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE TABLE IF NOT EXISTS tenants (id TEXT PRIMARY KEY, plan TEXT, tier_name TEXT, status TEXT, live_until TIMESTAMPTZ, access_until TIMESTAMPTZ, founding_license BOOLEAN, token_hash TEXT UNIQUE, kms_key_id TEXT, price_paid_usd INT, cases_allowed INT, basins_allowed INT, features JSONB);
CREATE TABLE IF NOT EXISTS tenant_basins (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id TEXT REFERENCES tenants(id) ON DELETE CASCADE, basin_id TEXT, basin_name TEXT, UNIQUE(tenant_id, basin_id));
CREATE TABLE IF NOT EXISTS audit_log (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id TEXT, action TEXT, request_id TEXT, timestamp TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS evidence_sources (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), source_type TEXT, url TEXT, title TEXT);
CREATE TABLE IF NOT EXISTS opportunities (id TEXT PRIMARY KEY, basin_id TEXT, basin_name TEXT, tier_required TEXT, tier_min_price INT, county TEXT, operator TEXT, facts JSONB, inferences JSONB, hypothesis TEXT, unknown_data JSONB, opportunity_statement TEXT, what_collected JSONB, how_connected TEXT, what_you_had_not_seen TEXT, verification_notes TEXT, temporal_claim TEXT, temporal_evidence_id UUID, bwpd_projected JSONB, verification_status TEXT, public_evidence_count INT, decision TEXT, created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS user_private_uploads (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id TEXT REFERENCES tenants(id) ON DELETE CASCADE, basin_id TEXT, opportunity_id TEXT, upload_type TEXT, filename TEXT, mime_type TEXT, size_bytes INT, data_encrypted TEXT, parsed_summary JSONB, created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS opportunity_recalculations (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id TEXT REFERENCES tenants(id) ON DELETE CASCADE, opportunity_id TEXT, private_upload_ids UUID[], verification_status TEXT, public_evidence INT, private_evidence INT, remaining_unknowns INT, calculation_status TEXT, result JSONB, algorithm_version TEXT, request_id TEXT, created_at TIMESTAMPTZ DEFAULT NOW());
-- FIX 401 AUTO-SEED
INSERT INTO tenants (id, plan, tier_name, status, live_until, access_until, founding_license, token_hash, kms_key_id, price_paid_usd, cases_allowed, basins_allowed, features) VALUES ('argos_ent_pilot_90','pilot_90','Starter','active',NOW()+INTERVAL '90 days',NOW()+INTERVAL '90 days',false,'7be066312bd91c7faa402bfac63ddea16de0fab589b53aba564e79b9c9b82411','kms_90',90000,5,1,'{}'::jsonb) ON CONFLICT (id) DO UPDATE SET token_hash=EXCLUDED.token_hash, status='active';
INSERT INTO tenant_basins (tenant_id, basin_id, basin_name) VALUES ('argos_ent_pilot_90','midland','Midland Basin') ON CONFLICT (tenant_id, basin_id) DO NOTHING;
INSERT INTO evidence_sources (id, source_type, url, title) VALUES ('00000000-0000-0000-0000-000000000001','ENERGYNOW','https://energynow.com','FireBird') ON CONFLICT (id) DO NOTHING;
INSERT INTO opportunities (id, basin_id, basin_name, tier_required, tier_min_price, county, operator, facts, inferences, hypothesis, unknown_data, opportunity_statement, what_collected, how_connected, what_you_had_not_seen, verification_notes, temporal_claim, temporal_evidence_id, bwpd_projected, verification_status, public_evidence_count, decision) VALUES ('CASE_001_MIDLAND_FIREBIRD_54K','midland','Midland Basin','pilot_90',90000,'Upton','Continental Resources','[]'::jsonb,'[]'::jsonb,'test','[]'::jsonb,'OPORTUNIDAD','[]'::jsonb,'cruce','no vista','verificar','Aug 2026','00000000-0000-0000-0000-000000000001','{}'::jsonb,'PARTIALLY_VERIFIED',1,'REFORMULAR') ON CONFLICT (id) DO NOTHING;
